import '../api/api_exception.dart';

String mapApiErrorMessage(String code, String fallback) {
  final message = switch (code) {
    'AUTH_REQUIRED' || 'UNAUTHORIZED' => '请先配置有效的 API Key。',
    'AUTH_INVALID_API_KEY' => 'API Key 无效。',
    'AUTH_USER_NOT_FOUND' => '用户不存在。',
    'AUTH_USER_DISABLED' => '用户已禁用。',
    'AUTH_ADMIN_REQUIRED' => '需要管理员权限。',
    'AUTH_KEY_NOT_RECOVERABLE' => 'API Key 只能重置，不能找回。',
    'AUTH_RECOVERY_LOCAL_ONLY' => '该恢复操作只能在本机执行。',
    'PERMISSION_DENIED' => '当前 API Key 没有执行该操作的权限。',
    'UPLOAD_FILE_TOO_LARGE' => '上传文件超过大小限制。',
    'GPU_BUSY' => 'GPU 正在执行其他任务，请稍后重试。',
    'DOWNLOAD_NOT_FOUND' => '下载任务不存在。',
    'DOWNLOAD_ALREADY_RUNNING' => '同一模型仓库已有下载任务正在运行。',
    'DOWNLOAD_AUTH_REQUIRED' => '下载源需要授权，请配置有效 Token。',
    'DOWNLOAD_REPO_NOT_FOUND' => '未找到指定模型仓库。',
    'DOWNLOAD_REVISION_NOT_FOUND' => '未找到指定 revision。',
    'DOWNLOAD_DISK_FULL' => '磁盘空间不足，无法继续下载。',
    'DOWNLOAD_NETWORK_ERROR' => '下载网络错误，请稍后重试。',
    'DOWNLOAD_CANCEL_REQUESTED' => '取消请求已提交，当前文件传输可能稍后停止。',
    'DOWNLOAD_CANCELLED' => '下载已取消。',
    'JOB_CANCEL_NOT_ALLOWED' => '该任务已结束，不能取消。',
    'DOWNLOAD_CANCEL_NOT_ALLOWED' => '该下载任务当前不能取消。',
    'DOWNLOAD_RECORD_DELETE_NOT_ALLOWED' => '下载任务仍在运行，不能删除记录。',
    'DOWNLOAD_LOCAL_FILES_NOT_FOUND' => '本地缓存中未找到该模型文件。',
    'DOWNLOAD_TEMP_CLEANUP_FAILED' => '下载临时目录清理失败。',
    'DOWNLOAD_RETRY_NOT_ALLOWED' => '该下载任务当前不能重试。',
    'DOWNLOAD_FAILED' => '下载失败，请查看任务详情。',
    'DOWNLOAD_VALIDATION_FAILED' => '下载结果校验失败。',
    'DOWNLOAD_MODEL_SCAN_FAILED' => '下载完成，但模型扫描注册失败。',
    'DOWNLOAD_MODEL_UNSUPPORTED' => '下载完成，但模型格式暂不支持。',
    'DOWNLOAD_PROVIDER_NOT_SUPPORTED' => '不支持该下载源。',
    'DOWNLOAD_PROVIDER_NOT_INSTALLED' => '当前环境未安装该下载源依赖。',
    'MODELSCOPE_AUTH_REQUIRED' => '魔塔社区认证失败，请检查 Token。',
    'MODELSCOPE_REPO_NOT_FOUND' => '魔塔社区未找到该模型。',
    'MODELSCOPE_NETWORK_ERROR' => '魔塔社区网络请求失败。',
    'MODELSCOPE_LOCAL_FILES_NOT_FOUND' => '魔塔本地缓存中未找到该模型。',
    'MODELSCOPE_DOWNLOAD_FAILED' => '魔塔模型下载失败。',
    'MODEL_NOT_FOUND' => '未找到指定模型，请先扫描、下载或注册模型。',
    'MODEL_LOAD_BUSY' => '模型正在加载或 GPU 正忙，请稍后重试。',
    'MODEL_LOAD_FAILED' => '模型加载失败，请查看后端日志。',
    'MODEL_UNLOAD_FAILED' => '模型卸载失败，请查看后端日志。',
    'MODEL_DELETE_CONFIRM_REQUIRED' => '删除模型需要二次确认。',
    'MODEL_DELETE_FAILED' => '模型删除失败，请查看后端日志。',
    'ADAPTER_MODEL_REQUIRED' => '请先选择或加载基础模型。',
    'ADAPTER_INCOMPATIBLE' => 'Adapter 与当前基础模型不兼容。',
    'ADAPTER_NOT_FOUND' => '未找到指定 Adapter。',
    'ADAPTER_OPERATION_FAILED' => 'Adapter 操作失败，请查看后端日志。',
    'PEFT_NOT_AVAILABLE' => '当前模型或环境不支持 PEFT Adapter 操作。',
    'RAG_QUERY_INVALID' => 'RAG 查询问题不能为空。',
    'RAG_PATH_NOT_ALLOWED' => '当前 API Key 无权读取该本地路径，或路径不在允许目录内。',
    'VISION_PATH_NOT_ALLOWED' => '当前 API Key 无权读取该图片路径，或路径不在允许目录内。',
    'DIAGNOSTICS_EXPORT_FAILED' => '诊断包导出失败，请查看后端日志。',
    'STORAGE_CLEANUP_FAILED' => '存储清理失败，请查看后端日志。',
    'PROMPT_TEMPLATE_NOT_FOUND' => '未找到指定 Prompt 模板。',
    'PROMPT_TEMPLATE_VERSION_NOT_FOUND' => '未找到指定 Prompt 模板版本。',
    'PROMPT_INVALID_TYPE' => 'Prompt 模板类型无效。',
    'PROMPT_INVALID_SCOPE' => 'Prompt 模板作用域无效。',
    'PROMPT_INVALID_VARIABLE_SCHEMA' => 'Prompt 变量定义不是合法 JSON schema。',
    'PROMPT_MISSING_REQUIRED_VARIABLES' => 'Prompt 缺少必填变量。',
    'PROMPT_RENDER_TOO_LONG' => 'Prompt 渲染结果过长。',
    'PROMPT_VERSION_MISMATCH' => 'Prompt 模板版本不属于该模板。',
    'PROMPT_PROJECT_NOT_FOUND' => '未找到关联的小说项目。',
    'PROMPT_CHAPTER_NOT_FOUND' => '未找到关联的章节。',
    'PROMPT_FEATURE_DISABLED' => 'Prompt Studio 当前未启用。',
    'PROMPT_DEFAULT_TEMPLATE_FAILED' => '默认 Prompt 模板初始化失败。',
    'CONTEXT_FEATURE_DISABLED' => 'Context Assembler 当前未启用。',
    'CONTEXT_PROJECT_NOT_FOUND' => '未找到指定小说项目。',
    'CONTEXT_CHAPTER_NOT_FOUND' => '未找到指定章节，或章节不属于当前项目。',
    'CONTEXT_SCENE_NOT_FOUND' => '未找到指定场景，或场景不属于当前章节。',
    'CONTEXT_TEMPLATE_NOT_FOUND' => '未找到用于预览的 Prompt 模板。',
    'CONTEXT_TEMPLATE_VERSION_NOT_FOUND' => '未找到指定 Prompt 模板版本。',
    'CONTEXT_ASSEMBLY_FAILED' => '上下文装配失败，请查看后端日志。',
    'CONTEXT_RENDER_FAILED' => '上下文已装配，但 Prompt 渲染失败。',
    'CONTEXT_BUDGET_EXCEEDED' => '核心上下文仍超出预算，请提高预算或减少输入。',
    'CONTEXT_TRUNCATED' => '上下文超出预算，已裁剪低优先级资料。',
    'CONTEXT_INVALID_BUDGET' => '上下文预算参数无效。',
    'CONTEXT_VARIABLES_INVALID' => '上下文变量必须是有效的 JSON 对象。',
    'WRITING_FEATURE_DISABLED' => 'Writing Workspace 当前未启用。',
    'WRITING_PROJECT_NOT_FOUND' => '未找到指定小说项目。',
    'WRITING_CHAPTER_NOT_FOUND' => '未找到指定章节，或章节不属于当前项目。',
    'WRITING_SCENE_NOT_FOUND' => '未找到指定场景，或场景不属于当前章节。',
    'WRITING_TEMPLATE_NOT_FOUND' => '未找到用于生成的 Prompt 模板。',
    'WRITING_CONTEXT_NOT_FOUND' => '未找到指定上下文记录。',
    'WRITING_MODEL_NOT_FOUND' => '未找到指定本地模型。',
    'WRITING_MODEL_NOT_LOADED' => '本地模型暂时无法加载，请检查模型状态。',
    'WRITING_MODEL_NOT_SUPPORTED' => '当前模型不支持文本生成。',
    'WRITING_ADAPTER_NOT_FOUND' => '未找到指定 Adapter，或 Adapter 无法加载。',
    'WRITING_INVALID_MODE' => '写作模式无效。',
    'WRITING_INVALID_TARGET_LENGTH' => '目标长度参数无效。',
    'WRITING_INVALID_GENERATION_PARAMS' => '生成参数超出允许范围。',
    'WRITING_CONTEXT_ASSEMBLY_FAILED' => '写作上下文装配失败。',
    'WRITING_PROMPT_RENDER_FAILED' => '写作 Prompt 渲染失败。',
    'WRITING_GENERATION_FAILED' => '本地小说生成失败，请检查后端日志。',
    'WRITING_STREAM_FAILED' => '流式生成中断，请检查已保存的生成记录。',
    'WRITING_CANCEL_NOT_SUPPORTED' => '当前生成任务不能取消。',
    'WRITING_SAVE_TARGET_NOT_ALLOWED' => '阶段 4 只允许保存到草稿或摘要。',
    'WRITING_GENERATION_NOT_FOUND' => '未找到指定生成记录。',
    'REVISION_FEATURE_DISABLED' => 'Revision Review 当前未启用。',
    'REVISION_NOT_FOUND' => '未找到指定修订记录。',
    'REVISION_PROJECT_NOT_FOUND' => '未找到修订所属小说项目。',
    'REVISION_CHAPTER_NOT_FOUND' => '未找到修订所属章节。',
    'REVISION_GENERATION_NOT_FOUND' => '未找到指定生成记录，无法创建修订。',
    'REVISION_ORIGINAL_TEXT_EMPTY' => '修订原文不能为空。',
    'REVISION_EDITED_TEXT_EMPTY' => '人工修改稿不能为空。',
    'REVISION_INVALID_TAG' => '修订标签无效。',
    'REVISION_INVALID_SCORE' => '用户评分必须是 1 到 5。',
    'REVISION_INVALID_STATUS' => '审核状态无效。',
    'REVISION_DIFF_FAILED' => '后端生成 Diff 失败。',
    'REVISION_CONFLICT' => '修订记录已被更新，请刷新后再保存。',
    'REVISION_AUTOSAVE_FAILED' => '自动保存失败，但不影响继续编辑。',
    'REVISION_DATASET_CANDIDATE_REQUIRES_APPROVAL' => '进入数据集候选前需要先审核通过。',
    'REVISION_PERMISSION_DENIED' => '当前账号没有修订操作权限。',
    'DATASET_FEATURE_DISABLED' => 'Dataset Builder 当前未启用。',
    'DATASET_NOT_FOUND' => '未找到指定 Dataset。',
    'DATASET_SAMPLE_NOT_FOUND' => '未找到指定样本。',
    'DATASET_EXPORT_NOT_FOUND' => '未找到指定导出记录。',
    'DATASET_PROJECT_NOT_FOUND' => '未找到指定小说项目。',
    'DATASET_REVISION_NOT_FOUND' => '未找到可构建样本的 Revision。',
    'DATASET_REVISION_NOT_ACCEPTED' => '请先将 Revision 标记为 Dataset Candidate。',
    'DATASET_REVISION_NOT_APPROVED' => '建议先审核通过 Revision。',
    'DATASET_INVALID_TYPE' => 'Dataset 类型无效。',
    'DATASET_INVALID_STATUS' => 'Dataset 或样本状态无效。',
    'DATASET_INVALID_SAMPLE_TYPE' => '样本类型无效。',
    'DATASET_INVALID_EXPORT_FORMAT' => '导出格式无效。',
    'DATASET_SAMPLE_EMPTY_INSTRUCTION' => '样本 instruction 不能为空。',
    'DATASET_SAMPLE_EMPTY_OUTPUT' => '样本 output 不能为空。',
    'DATASET_SAMPLE_DUPLICATE' => '该 Dataset 中已存在相同内容的样本。',
    'DATASET_SAMPLE_UNCHANGED_FROM_ORIGINAL' => '样本与原始模型输出过于接近，请检查修订幅度。',
    'DATASET_SAMPLE_INPUT_LONG' => '样本 input 较长，阶段 6 仅记录警告。',
    'DATASET_NO_APPROVED_SAMPLES' => '没有可导出的 approved samples。',
    'DATASET_EXPORT_FAILED' => 'Dataset JSONL 导出失败。',
    'DATASET_EXPORT_PATH_INVALID' => '导出路径必须位于 data/datasets 下。',
    'DATASET_VERSION_NOT_IMPLEMENTED' => '该 DatasetVersion 操作尚未实现。',
    'DATASET_VERSION_NOT_FOUND' => '未找到指定 DatasetVersion。',
    'DATASET_VERSION_ALREADY_EXISTS' => '该 DatasetVersion 已存在。',
    'DATASET_VERSION_IMMUTABLE' => '冻结后的 DatasetVersion 不可编辑。',
    'DATASET_FREEZE_NOT_READY' => '只有 ready 或 dirty 状态的 Dataset 可以冻结。',
    'DATASET_FREEZE_NO_APPROVED_SAMPLES' => '没有 approved samples，无法冻结。',
    'DATASET_FREEZE_FAILED' => 'Dataset 冻结失败，请查看后端日志。',
    'DATASET_DIRTY_MARK_FAILED' => 'Dataset dirty 标记失败。',
    'DATASET_MANIFEST_NOT_FOUND' => '未找到 Dataset manifest。',
    'DATASET_MANIFEST_INVALID' => 'Dataset manifest 内容无效。',
    'DATASET_SPLIT_INVALID' => 'train / validation split 参数无效。',
    'DATASET_SPLIT_TOO_SMALL' => '样本太少，验证集切分不稳定。',
    'DATASET_EXACT_DUPLICATE' => '发现完全重复样本。',
    'DATASET_NEAR_DUPLICATE' => '发现近重复样本。',
    'DATASET_TOKEN_STATS_FAILED' => 'Token 统计失败。',
    'DATASET_RECIPE_NOT_FOUND' => '未找到训练配方。',
    'DATASET_RECIPE_INVALID_METHOD' => '训练配方 method 无效。',
    'DATASET_RECIPE_RECOMMEND_FAILED' => '训练配方推荐失败。',
    'DATASET_RECIPE_CONFIRM_FAILED' => '训练配方确认失败。',
    'DATASET_RECIPE_ALREADY_CONFIRMED' => '训练配方已经确认。',
    'DATASET_TOO_SMALL_FOR_TRAINING' => '样本数量较少，训练容易过拟合。',
    'DATASET_NO_VALIDATION_SPLIT' => '当前 DatasetVersion 没有验证集。',
    'DATASET_TRAINING_NOT_IMPLEMENTED' => '阶段 7 不启动训练。',
    'DATASET_PERMISSION_DENIED' => '当前账号没有 Dataset Builder 权限。',
    'FINETUNE_FEATURE_DISABLED' => 'Fine-tune Center 当前未启用。',
    'FINETUNE_RUN_NOT_FOUND' => '未找到指定 Fine-tune run。',
    'FINETUNE_DATASET_VERSION_NOT_FOUND' => '未找到指定 DatasetVersion。',
    'FINETUNE_DATASET_VERSION_NOT_FROZEN' => '只能使用 frozen DatasetVersion 训练。',
    'FINETUNE_DATASET_MANIFEST_NOT_FOUND' => '未找到 DatasetVersion manifest。',
    'FINETUNE_DATASET_MANIFEST_INVALID' =>
      'DatasetVersion manifest 无效或 hash 不匹配。',
    'FINETUNE_TRAIN_FILE_NOT_FOUND' => '未找到 train.jsonl。',
    'FINETUNE_RECIPE_NOT_FOUND' => '未找到训练配方。',
    'FINETUNE_RECIPE_NOT_CONFIRMED' => '训练配方尚未确认。',
    'FINETUNE_RECIPE_DATASET_MISMATCH' => '训练配方不属于该 DatasetVersion。',
    'FINETUNE_BASE_MODEL_NOT_FOUND' => '未找到指定基础模型。',
    'FINETUNE_BASE_MODEL_NOT_SUPPORTED' => '该基础模型不支持 LoRA/QLoRA 训练。',
    'FINETUNE_ADAPTER_NAME_INVALID' => 'Adapter 名称无效。',
    'FINETUNE_ADAPTER_NAME_CONFLICT' => 'Adapter 名称已存在。',
    'FINETUNE_INVALID_METHOD' => '训练方式必须是 LoRA 或 QLoRA。',
    'FINETUNE_INVALID_CONFIG' => '训练配置无效。',
    'FINETUNE_DEPENDENCY_MISSING' => '缺少训练依赖，请安装本地 fine-tune 依赖。',
    'FINETUNE_GPU_NOT_AVAILABLE' => '未检测到可用于训练的 GPU。',
    'FINETUNE_INSUFFICIENT_VRAM' => '显存或磁盘空间不足。',
    'FINETUNE_OUTPUT_PATH_INVALID' => '训练输出路径无效。',
    'FINETUNE_PREFLIGHT_FAILED' => 'Fine-tune preflight 未通过。',
    'FINETUNE_JOB_CREATE_FAILED' => '训练任务入队失败。',
    'FINETUNE_TRAINING_FAILED' => '训练失败，请查看脱敏日志。',
    'FINETUNE_CANCEL_NOT_SUPPORTED' => '当前训练任务不能取消。',
    'FINETUNE_CHECKPOINT_NOT_FOUND' => '未找到指定 checkpoint。',
    'FINETUNE_RESUME_FAILED' => '无法从 checkpoint 恢复训练。',
    'FINETUNE_ADAPTER_EXPORT_FAILED' => '训练完成但 Adapter 导出失败。',
    'FINETUNE_ADAPTER_REGISTER_FAILED' => 'Adapter 注册失败。',
    'FINETUNE_PERMISSION_DENIED' => '当前账号没有 Fine-tune Center 权限。',
    'ADAPTER_EVAL_FEATURE_DISABLED' => 'Adapter Evaluation 当前未启用。',
    'ADAPTER_EVAL_SESSION_NOT_FOUND' => '未找到指定 Adapter 评估会话。',
    'ADAPTER_EVAL_CASE_NOT_FOUND' => '未找到指定评估用例。',
    'ADAPTER_EVAL_RESULT_NOT_FOUND' => '未找到指定评估结果。',
    'ADAPTER_EVAL_SCORE_NOT_FOUND' => '未找到指定人工评分。',
    'ADAPTER_EVAL_REPORT_NOT_FOUND' => '未找到指定评估报告。',
    'ADAPTER_EVAL_BASE_MODEL_NOT_FOUND' => '未找到用于对比的基础模型。',
    'ADAPTER_EVAL_ADAPTER_NOT_FOUND' => '未找到待评估的 Adapter。',
    'ADAPTER_EVAL_ADAPTER_INCOMPATIBLE' => 'Adapter 与基础模型不兼容。',
    'ADAPTER_EVAL_FINETUNE_RUN_NOT_FOUND' => '未找到关联的 Fine-tune Run。',
    'ADAPTER_EVAL_FINETUNE_RUN_NOT_COMPLETED' =>
      '只有已完成且已注册 Adapter 的训练 Run 可以评估。',
    'ADAPTER_EVAL_PROJECT_NOT_FOUND' => '未找到评估所属小说项目。',
    'ADAPTER_EVAL_CHAPTER_NOT_FOUND' => '未找到评估所属章节。',
    'ADAPTER_EVAL_TEMPLATE_NOT_FOUND' => '未找到用于评估的 Prompt 模板。',
    'ADAPTER_EVAL_CONTEXT_FAILED' => '评估上下文装配失败。',
    'ADAPTER_EVAL_PROMPT_RENDER_FAILED' => '评估 Prompt 渲染失败。',
    'ADAPTER_EVAL_GENERATION_FAILED' => '评估生成失败，请检查本地模型和 Adapter 状态。',
    'ADAPTER_EVAL_INVALID_SCORE' => '人工评分必须在 1 到 5 之间。',
    'ADAPTER_EVAL_INVALID_WINNER' => '评估胜出方必须是 base、adapter、tie 或 none。',
    'ADAPTER_EVAL_CASE_NOT_READY' => '评估用例尚未准备好，请先生成冻结 Prompt。',
    'ADAPTER_EVAL_RESULT_PAIR_INCOMPLETE' => '基础模型和 Adapter 的结果不完整，暂不能评分或建报告。',
    'ADAPTER_EVAL_REPORT_FAILED' => '评估报告生成失败。',
    'ADAPTER_EVAL_REVISION_CREATE_FAILED' => '从评估结果创建 Revision 失败。',
    'ADAPTER_EVAL_PERMISSION_DENIED' => '当前账号没有 Adapter Evaluation 操作权限。',
    'INTERNAL_ERROR' => '操作失败，请查看后端日志。',
    'BENCHMARK_OOM' => 'Benchmark 显存不足，请降低上下文或输出长度。',
    _ => fallback,
  };
  return message.trim().isEmpty ? '操作失败，请查看后端日志。' : message;
}

StudioApiException exceptionForApiError({
  required int statusCode,
  required String code,
  required String message,
}) {
  final mapped = mapApiErrorMessage(code, message);
  if (statusCode == 401 ||
      code == 'AUTH_REQUIRED' ||
      code == 'AUTH_INVALID_API_KEY' ||
      code == 'UNAUTHORIZED') {
    return AuthRequiredException(mapped, code: code, statusCode: statusCode);
  }
  if (statusCode == 403 ||
      code == 'PERMISSION_DENIED' ||
      code == 'AUTH_ADMIN_REQUIRED') {
    return PermissionDeniedException(
      mapped,
      code: code,
      statusCode: statusCode,
    );
  }
  return StudioApiException(mapped, code: code, statusCode: statusCode);
}
