import '../api/api_exception.dart';

String mapApiErrorMessage(String code, String fallback) {
  final message = switch (code) {
    'AUTH_REQUIRED' || 'UNAUTHORIZED' => '请先配置有效的 API Key。',
    'AUTH_INVALID_API_KEY' => 'API Key 无效。',
    'AUTH_USER_NOT_FOUND' => '用户不存在。',
    'AUTH_USER_DISABLED' => '用户已禁用。',
    'AUTH_ADMIN_REQUIRED' => '需要管理员权限。',
    'AUTH_KEY_NOT_RECOVERABLE' => 'API Key 只能重置，不能找回。',
    'AUTH_RECOVERY_LOCAL_ONLY' => '该恢复操作只能在本机执行。',
    'PERMISSION_DENIED' => '当前 API Key 没有执行该操作的权限。',
    'UPLOAD_FILE_TOO_LARGE' => '上传文件超过大小限制。',
    'GPU_BUSY' => 'GPU 正在执行其他任务，请稍后重试。',
    'DOWNLOAD_NOT_FOUND' => '下载任务不存在。',
    'DOWNLOAD_ALREADY_RUNNING' => '同一模型仓库已有下载任务正在运行。',
    'DOWNLOAD_AUTH_REQUIRED' => '下载源需要授权，请配置有效 Token。',
    'DOWNLOAD_REPO_NOT_FOUND' => '未找到指定模型仓库。',
    'DOWNLOAD_REVISION_NOT_FOUND' => '未找到指定 revision。',
    'DOWNLOAD_DISK_FULL' => '磁盘空间不足，无法继续下载。',
    'DOWNLOAD_NETWORK_ERROR' => '下载网络错误，请稍后重试。',
    'DOWNLOAD_CANCEL_REQUESTED' => '取消请求已提交，当前文件传输可能稍后停止。',
    'DOWNLOAD_CANCELLED' => '下载已取消。',
    'JOB_CANCEL_NOT_ALLOWED' => '该任务已结束，不能取消。',
    'DOWNLOAD_CANCEL_NOT_ALLOWED' => '该下载任务当前不能取消。',
    'DOWNLOAD_RECORD_DELETE_NOT_ALLOWED' => '下载任务仍在运行，不能删除记录。',
    'DOWNLOAD_LOCAL_FILES_NOT_FOUND' => '本地缓存中未找到该模型文件。',
    'DOWNLOAD_TEMP_CLEANUP_FAILED' => '下载临时目录清理失败。',
    'DOWNLOAD_RETRY_NOT_ALLOWED' => '该下载任务当前不能重试。',
    'DOWNLOAD_FAILED' => '下载失败，请查看任务详情。',
    'DOWNLOAD_VALIDATION_FAILED' => '下载结果校验失败。',
    'DOWNLOAD_MODEL_SCAN_FAILED' => '下载完成，但模型扫描注册失败。',
    'DOWNLOAD_MODEL_UNSUPPORTED' => '下载完成，但模型格式暂不支持。',
    'DOWNLOAD_PROVIDER_NOT_SUPPORTED' => '不支持该下载源。',
    'DOWNLOAD_PROVIDER_NOT_INSTALLED' => '当前环境未安装该下载源依赖。',
    'MODELSCOPE_AUTH_REQUIRED' => '魔塔社区认证失败，请检查 Token。',
    'MODELSCOPE_REPO_NOT_FOUND' => '魔塔社区未找到该模型。',
    'MODELSCOPE_NETWORK_ERROR' => '魔塔社区网络请求失败。',
    'MODELSCOPE_LOCAL_FILES_NOT_FOUND' => '魔塔本地缓存中未找到该模型。',
    'MODELSCOPE_DOWNLOAD_FAILED' => '魔塔模型下载失败。',
    'MODEL_NOT_FOUND' => '未找到指定模型，请先扫描、下载或注册模型。',
    'MODEL_LOAD_BUSY' => '模型正在加载或 GPU 正忙，请稍后重试。',
    'MODEL_LOAD_FAILED' => '模型加载失败，请查看后端日志。',
    'MODEL_UNLOAD_FAILED' => '模型卸载失败，请查看后端日志。',
    'MODEL_DELETE_CONFIRM_REQUIRED' => '删除模型需要二次确认。',
    'MODEL_DELETE_FAILED' => '模型删除失败，请查看后端日志。',
    'ADAPTER_MODEL_REQUIRED' => '请先选择或加载基础模型。',
    'ADAPTER_INCOMPATIBLE' => 'Adapter 与当前基础模型不兼容。',
    'ADAPTER_NOT_FOUND' => '未找到指定 Adapter。',
    'ADAPTER_OPERATION_FAILED' => 'Adapter 操作失败，请查看后端日志。',
    'PEFT_NOT_AVAILABLE' => '当前模型或环境不支持 PEFT Adapter 操作。',
    'RAG_QUERY_INVALID' => 'RAG 查询问题不能为空。',
    'RAG_PATH_NOT_ALLOWED' => '当前 API Key 无权读取该本地路径，或路径不在允许目录内。',
    'VISION_PATH_NOT_ALLOWED' => '当前 API Key 无权读取该图片路径，或路径不在允许目录内。',
    'DIAGNOSTICS_EXPORT_FAILED' => '诊断包导出失败，请查看后端日志。',
    'STORAGE_CLEANUP_FAILED' => '存储清理失败，请查看后端日志。',
    'PROMPT_TEMPLATE_NOT_FOUND' => '未找到指定 Prompt 模板。',
    'PROMPT_TEMPLATE_VERSION_NOT_FOUND' => '未找到指定 Prompt 模板版本。',
    'PROMPT_INVALID_TYPE' => 'Prompt 模板类型无效。',
    'PROMPT_INVALID_SCOPE' => 'Prompt 模板作用域无效。',
    'PROMPT_INVALID_VARIABLE_SCHEMA' => 'Prompt 变量定义不是合法 JSON schema。',
    'PROMPT_MISSING_REQUIRED_VARIABLES' => 'Prompt 缺少必填变量。',
    'PROMPT_RENDER_TOO_LONG' => 'Prompt 渲染结果过长。',
    'PROMPT_VERSION_MISMATCH' => 'Prompt 模板版本不属于该模板。',
    'PROMPT_PROJECT_NOT_FOUND' => '未找到关联的小说项目。',
    'PROMPT_CHAPTER_NOT_FOUND' => '未找到关联的章节。',
    'PROMPT_FEATURE_DISABLED' => 'Prompt Studio 当前未启用。',
    'PROMPT_DEFAULT_TEMPLATE_FAILED' => '默认 Prompt 模板初始化失败。',
    'CONTEXT_FEATURE_DISABLED' => 'Context Assembler 当前未启用。',
    'CONTEXT_PROJECT_NOT_FOUND' => '未找到指定小说项目。',
    'CONTEXT_CHAPTER_NOT_FOUND' => '未找到指定章节，或章节不属于当前项目。',
    'CONTEXT_SCENE_NOT_FOUND' => '未找到指定场景，或场景不属于当前章节。',
    'CONTEXT_TEMPLATE_NOT_FOUND' => '未找到用于预览的 Prompt 模板。',
    'CONTEXT_TEMPLATE_VERSION_NOT_FOUND' => '未找到指定 Prompt 模板版本。',
    'CONTEXT_ASSEMBLY_FAILED' => '上下文装配失败，请查看后端日志。',
    'CONTEXT_RENDER_FAILED' => '上下文已装配，但 Prompt 渲染失败。',
    'CONTEXT_BUDGET_EXCEEDED' => '核心上下文仍超出预算，请提高预算或减少输入。',
    'CONTEXT_TRUNCATED' => '上下文超出预算，已裁剪低优先级资料。',
    'CONTEXT_INVALID_BUDGET' => '上下文预算参数无效。',
    'CONTEXT_VARIABLES_INVALID' => '上下文变量必须是有效的 JSON 对象。',
    'WRITING_FEATURE_DISABLED' => 'Writing Workspace 当前未启用。',
    'WRITING_PROJECT_NOT_FOUND' => '未找到指定小说项目。',
    'WRITING_CHAPTER_NOT_FOUND' => '未找到指定章节，或章节不属于当前项目。',
    'WRITING_SCENE_NOT_FOUND' => '未找到指定场景，或场景不属于当前章节。',
    'WRITING_TEMPLATE_NOT_FOUND' => '未找到用于生成的 Prompt 模板。',
    'WRITING_CONTEXT_NOT_FOUND' => '未找到指定上下文记录。',
    'WRITING_MODEL_NOT_FOUND' => '未找到指定本地模型。',
    'WRITING_MODEL_NOT_LOADED' => '本地模型暂时无法加载，请检查模型状态。',
    'WRITING_MODEL_NOT_SUPPORTED' => '当前模型不支持文本生成。',
    'WRITING_ADAPTER_NOT_FOUND' => '未找到指定 Adapter，或 Adapter 无法加载。',
    'WRITING_INVALID_MODE' => '写作模式无效。',
    'WRITING_INVALID_TARGET_LENGTH' => '目标长度参数无效。',
    'WRITING_INVALID_GENERATION_PARAMS' => '生成参数超出允许范围。',
    'WRITING_CONTEXT_ASSEMBLY_FAILED' => '写作上下文装配失败。',
    'WRITING_PROMPT_RENDER_FAILED' => '写作 Prompt 渲染失败。',
    'WRITING_GENERATION_FAILED' => '本地小说生成失败，请检查后端日志。',
    'WRITING_STREAM_FAILED' => '流式生成中断，请检查已保存的生成记录。',
    'WRITING_CANCEL_NOT_SUPPORTED' => '当前生成任务不能取消。',
    'WRITING_SAVE_TARGET_NOT_ALLOWED' => '阶段 4 只允许保存到草稿或摘要。',
    'WRITING_GENERATION_NOT_FOUND' => '未找到指定生成记录。',
    'REVISION_FEATURE_DISABLED' => 'Revision Review 当前未启用。',
    'REVISION_NOT_FOUND' => '未找到指定修订记录。',
    'REVISION_PROJECT_NOT_FOUND' => '未找到修订所属小说项目。',
    'REVISION_CHAPTER_NOT_FOUND' => '未找到修订所属章节。',
    'REVISION_GENERATION_NOT_FOUND' => '未找到指定生成记录，无法创建修订。',
    'REVISION_ORIGINAL_TEXT_EMPTY' => '修订原文不能为空。',
    'REVISION_EDITED_TEXT_EMPTY' => '人工修改稿不能为空。',
    'REVISION_INVALID_TAG' => '修订标签无效。',
    'REVISION_INVALID_SCORE' => '用户评分必须是 1 到 5。',
    'REVISION_INVALID_STATUS' => '审核状态无效。',
    'REVISION_DIFF_FAILED' => '后端生成 Diff 失败。',
    'REVISION_CONFLICT' => '修订记录已被更新，请刷新后再保存。',
    'REVISION_AUTOSAVE_FAILED' => '自动保存失败，但不影响继续编辑。',
    'REVISION_DATASET_CANDIDATE_REQUIRES_APPROVAL' => '进入数据集候选前需要先审核通过。',
    'REVISION_PERMISSION_DENIED' => '当前账号没有修订操作权限。',
    'INTERNAL_ERROR' => '操作失败，请查看后端日志。',
    'BENCHMARK_OOM' => 'Benchmark 显存不足，请降低上下文或输出长度。',
    _ => fallback,
  };
  return message.trim().isEmpty ? '操作失败，请查看后端日志。' : message;
}

StudioApiException exceptionForApiError({
  required int statusCode,
  required String code,
  required String message,
}) {
  final mapped = mapApiErrorMessage(code, message);
  if (statusCode == 401 ||
      code == 'AUTH_REQUIRED' ||
      code == 'AUTH_INVALID_API_KEY' ||
      code == 'UNAUTHORIZED') {
    return AuthRequiredException(mapped, code: code, statusCode: statusCode);
  }
  if (statusCode == 403 ||
      code == 'PERMISSION_DENIED' ||
      code == 'AUTH_ADMIN_REQUIRED') {
    return PermissionDeniedException(
      mapped,
      code: code,
      statusCode: statusCode,
    );
  }
  return StudioApiException(mapped, code: code, statusCode: statusCode);
}
