"""API error helpers with stable error codes."""

from __future__ import annotations

from fastapi import HTTPException

MODEL_NOT_LOADED = "MODEL_NOT_LOADED"
MODEL_NOT_FOUND = "MODEL_NOT_FOUND"
MODEL_LOADING = "MODEL_LOADING"
QUEUE_FULL = "QUEUE_FULL"
GENERATION_TIMEOUT = "GENERATION_TIMEOUT"
GENERATION_CANCELLED = "GENERATION_CANCELLED"
CUDA_OUT_OF_MEMORY = "CUDA_OUT_OF_MEMORY"
INVALID_MESSAGES = "INVALID_MESSAGES"
RAG_INDEX_INVALID = "RAG_INDEX_INVALID"
DEPENDENCY_MISSING = "DEPENDENCY_MISSING"
UNAUTHORIZED = "UNAUTHORIZED"
AUTH_REQUIRED = "AUTH_REQUIRED"
PERMISSION_DENIED = "PERMISSION_DENIED"
UPLOAD_FILENAME_INVALID = "UPLOAD_FILENAME_INVALID"
UPLOAD_EXTENSION_NOT_ALLOWED = "UPLOAD_EXTENSION_NOT_ALLOWED"
UPLOAD_FILE_TOO_LARGE = "UPLOAD_FILE_TOO_LARGE"
UPLOAD_SAVE_FAILED = "UPLOAD_SAVE_FAILED"
UPLOAD_TYPE_NOT_SUPPORTED = "UPLOAD_TYPE_NOT_SUPPORTED"
ASYNC_TASK_FAILED = "ASYNC_TASK_FAILED"
GPU_BUSY = "GPU_BUSY"
GPU_TASK_TIMEOUT = "GPU_TASK_TIMEOUT"
MODEL_LOAD_BUSY = "MODEL_LOAD_BUSY"
BENCHMARK_OOM = "BENCHMARK_OOM"
RAG_QUERY_INVALID = "RAG_QUERY_INVALID"
ADAPTER_MODEL_REQUIRED = "ADAPTER_MODEL_REQUIRED"
ADAPTER_NOT_FOUND = "ADAPTER_NOT_FOUND"
ADAPTER_INCOMPATIBLE = "ADAPTER_INCOMPATIBLE"
PEFT_NOT_AVAILABLE = "PEFT_NOT_AVAILABLE"
MODEL_DELETE_CONFIRM_REQUIRED = "MODEL_DELETE_CONFIRM_REQUIRED"
MODEL_DELETE_FAILED = "MODEL_DELETE_FAILED"
MODEL_LOAD_FAILED = "MODEL_LOAD_FAILED"
MODEL_UNLOAD_FAILED = "MODEL_UNLOAD_FAILED"
RAG_INGEST_FAILED = "RAG_INGEST_FAILED"
RAG_QUERY_FAILED = "RAG_QUERY_FAILED"
RAG_PATH_NOT_ALLOWED = "RAG_PATH_NOT_ALLOWED"
VISION_ANALYZE_FAILED = "VISION_ANALYZE_FAILED"
VISION_PATH_NOT_ALLOWED = "VISION_PATH_NOT_ALLOWED"
ADAPTER_OPERATION_FAILED = "ADAPTER_OPERATION_FAILED"
BENCHMARK_FAILED = "BENCHMARK_FAILED"
STORAGE_CLEANUP_FAILED = "STORAGE_CLEANUP_FAILED"
DIAGNOSTICS_EXPORT_FAILED = "DIAGNOSTICS_EXPORT_FAILED"
INTERNAL_ERROR = "INTERNAL_ERROR"
DOWNLOAD_NOT_FOUND = "DOWNLOAD_NOT_FOUND"
DOWNLOAD_ALREADY_RUNNING = "DOWNLOAD_ALREADY_RUNNING"
DOWNLOAD_AUTH_REQUIRED = "DOWNLOAD_AUTH_REQUIRED"
DOWNLOAD_REPO_NOT_FOUND = "DOWNLOAD_REPO_NOT_FOUND"
DOWNLOAD_REVISION_NOT_FOUND = "DOWNLOAD_REVISION_NOT_FOUND"
DOWNLOAD_DISK_FULL = "DOWNLOAD_DISK_FULL"
DOWNLOAD_NETWORK_ERROR = "DOWNLOAD_NETWORK_ERROR"
DOWNLOAD_CANCEL_REQUESTED = "DOWNLOAD_CANCEL_REQUESTED"
DOWNLOAD_CANCELLED = "DOWNLOAD_CANCELLED"
DOWNLOAD_RETRY_NOT_ALLOWED = "DOWNLOAD_RETRY_NOT_ALLOWED"
DOWNLOAD_FAILED = "DOWNLOAD_FAILED"
DOWNLOAD_VALIDATION_FAILED = "DOWNLOAD_VALIDATION_FAILED"
DOWNLOAD_MODEL_SCAN_FAILED = "DOWNLOAD_MODEL_SCAN_FAILED"
DOWNLOAD_MODEL_UNSUPPORTED = "DOWNLOAD_MODEL_UNSUPPORTED"


def error_payload(
    code: str,
    message: str,
    request_id: str | None = None,
    details: dict | None = None,
) -> dict:
    error: dict[str, object] = {
        "code": code,
        "message": message,
        "request_id": request_id or "",
    }
    if details:
        error["details"] = details
    return {"error": error}


def api_error(
    status_code: int,
    code: str,
    message: str,
    request_id: str | None = None,
    details: dict | None = None,
) -> HTTPException:
    return HTTPException(
        status_code=status_code,
        detail=error_payload(code, message, request_id, details),
    )
