"""Localize Flutter desktop visible UI strings to Simplified Chinese.

This script intentionally replaces only complete string-literal bodies in UI
surface files. It does not translate API paths, JSON keys, enum values, model
identifiers, or other protocol strings.
"""

import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
FLUTTER_LIB = ROOT / "apps" / "flutter_studio" / "lib"

TARGET_GLOBS = [
    "app/*.dart",
    "core/ui/*.dart",
    "core/backend/*.dart",
    "features/**/*_page.dart",
    "features/**/widgets/*.dart",
    "features/**/*controller.dart",
]


ZH: dict[str, str] = {
    # App shell / navigation.
    "LLM Studio": "LLM Studio",
    "Core": "核心",
    "Status": "状态",
    "Models": "模型",
    "Chat": "聊天",
    "Workflows": "工作流",
    "Downloads": "下载",
    "Adapters": "适配器",
    "Adapter": "适配器",
    "Benchmark": "基准测试",
    "System": "系统",
    "Storage": "存储",
    "Diagnostics": "诊断",
    "Creative": "创作",
    "Novel Studio": "小说工作台",
    "Projects": "项目",
    "Prompt Studio": "提示词工作室",
    "Context Preview": "上下文预览",
    "Context": "上下文",
    "Writing": "写作",
    "Revision": "修订",
    "Dataset": "数据集",
    "Fine-tune": "微调",
    "Adapter Eval": "适配器评估",
    "Memory": "记忆",
    "Evaluation": "评估",
    "Settings": "设置",
    "Product UI": "产品界面",
    "1. Projects": "1. 项目",
    "2. Prompt Studio": "2. 提示词工作室",
    "3. Context": "3. 上下文",
    "4. Writing": "4. 写作",
    "5. Revision": "5. 修订",
    "6. Dataset": "6. 数据集",
    "7. Version/Recipe": "7. 版本 / 配方",
    "8. Fine-tune": "8. 微调",
    "9. Adapter Eval": "9. 适配器评估",
    "10. Memory": "10. 记忆",
    "11. Evaluation": "11. 评估",
    "12. Product UI": "12. 产品界面",
    # Common actions / states.
    "Refresh": "刷新",
    "Retry": "重试",
    "Copy": "复制",
    "Open": "打开",
    "Close": "关闭",
    "Cancel": "取消",
    "Create": "创建",
    "Generate": "生成",
    "Start": "开始",
    "Stop": "停止",
    "Load": "加载",
    "Activate": "启用",
    "Deactivate": "停用",
    "Apply": "应用",
    "Approve": "批准",
    "Reject": "拒绝",
    "Archive": "归档",
    "Dismiss": "关闭",
    "Regenerate": "重新生成",
    "Resume": "恢复",
    "Ready": "就绪",
    "Active": "已启用",
    "Inactive": "未启用",
    "Busy": "忙碌",
    "Idle": "空闲",
    "Experimental": "实验性",
    "Unsupported": "不支持",
    "Incomplete": "不完整",
    "Cleanable": "可清理",
    "Protected": "受保护",
    "Approved": "已批准",
    "Added": "已新增",
    "Removed": "已删除",
    "All": "全部",
    "None": "无",
    "Fast": "快速",
    "Balanced": "均衡",
    "Quality": "质量优先",
    "Soft": "宽松",
    "Hard": "严格",
    "Error": "错误",
    "Errors": "错误",
    "Warnings": "警告",
    "Logs": "日志",
    "Category": "类别",
    "Name": "名称",
    "Title": "标题",
    "Description": "描述",
    "Type": "类型",
    "Role": "角色",
    "Style": "风格",
    "Content": "内容",
    "Overview": "概览",
    "Summary": "摘要",
    "Suggestion": "建议",
    "Evidence": "证据",
    "Limitations": "限制",
    "Metrics": "指标",
    "Findings": "发现项",
    "Reports": "报告",
    "Preflight": "预检",
    "Queue": "队列",
    "Jobs": "任务",
    "$runningJobs running": "$runningJobs 个运行中",
    "Health": "健康状态",
    "Capabilities": "能力",
    "Cases": "用例",
    "Samples": "样本",
    "Versions": "版本",
    "Revisions": "修订",
    "Generations": "生成记录",
    "Prompts": "提示词",
    "Chapters": "章节",
    "Characters": "人物",
    "Volumes": "分卷",
    "Plot": "剧情",
    "Timeline": "时间线",
    "World Bible": "世界观设定",
    "Project": "项目",
    "Project ID": "项目 ID",
    "Chapter": "章节",
    "Chapter ID": "章节 ID",
    "Character": "人物",
    "Model ID": "模型 ID",
    "Generation": "生成记录",
    "Blocks": "区块",
    "Original": "原文",
    "Edited": "修订稿",
    "Human Edited": "人工修订",
    "Model Original": "模型原文",
    "Adapter Result": "适配器结果",
    "Base Model 输出": "基础模型输出",
    "Adapter 输出": "适配器输出",
    "Model": "模型",
    "Current model": "当前模型",
    "GPU": "GPU",
    "BF16": "BF16",
    "LoRA": "LoRA",
    "QLoRA": "QLoRA",
    "Tokens": "Token",
    # Core UI.
    "Capability unavailable": "能力不可用",
    "Something needs attention": "需要处理的问题",
    "Loading...": "加载中...",
    "Copy error": "复制错误",
    "Open Settings": "打开设置",
    "$capabilityName is disabled or not exposed by the backend.": "$capabilityName 已禁用或后端未暴露。",
    "$featureName is not enabled by backend capabilities. Open Settings to verify the backend and feature flags.": "$featureName 未在后端能力中启用。请打开设置检查后端与功能开关。",
    # Backend / settings.
    "Backend has not started yet.": "后端尚未启动。",
    "Using remote backend.": "正在使用远程后端。",
    "Starting backend...": "正在启动后端...",
    "Backend stopped by Flutter.": "Flutter 已停止后端。",
    "Backend is already running.": "后端已在运行。",
    "Backend started by Flutter.": "Flutter 已启动后端。",
    "Automatic backend startup is only available on desktop.": "自动启动后端仅支持桌面端。",
    "Backend": "后端",
    "Backend logs": "后端日志",
    "Backend logs copied.": "后端日志已复制。",
    "No backend logs captured yet.": "还没有捕获到后端日志。",
    "Remote backend": "远程后端",
    "Local backend": "本地后端",
    "FastAPI base URL": "FastAPI 基础地址",
    "Local Python path": "本地 Python 路径",
    "Local backend root": "本地后端根目录",
    "Auto-start local backend": "自动启动本地后端",
    "Close local backend on app exit": "退出应用时关闭本地后端",
    "Connection settings": "连接设置",
    "Test backend": "测试后端",
    "Restart backend": "重启后端",
    "Stop backend": "停止后端",
    "Copy logs": "复制日志",
    "Need a support bundle?": "需要支持包？",
    "Diagnostics exports are redacted and exclude model weights, API keys, cookies, and document bodies.": "诊断导出会脱敏，并排除模型权重、API Key、Cookie 和文档正文。",
    "Release notes": "发布说明",
    "Release notes are packaged in docs/RELEASE_NOTES.md.": "发布说明已打包在 docs/RELEASE_NOTES.md。",
    "Auth recovery": "认证恢复",
    "User Management 仅 admin 可见。": "用户管理仅 admin 可见。",
    "Admin 密码丢失时不能通过远程 UI 重置。请在后端所在机器运行：": "admin 密码丢失时不能通过远程 UI 重置。请在后端所在机器运行：",
    "API Key 不能找回，只能由已认证 admin 重新生成。新 Key 只显示一次。": "API Key 不能找回，只能由已认证 admin 重新生成。新 Key 只显示一次。",
    "API Key regeneration failed.": "API Key 重新生成失败。",
    "Regenerate API Key": "重新生成 API Key",
    "New API Key": "新 API Key",
    "Clear auth": "清除认证",
    "Load users": "加载用户",
    "Current user: ${currentUser!.userId} (${currentUser!.role})": "当前用户：${currentUser!.userId}（${currentUser!.role}）",
    "Unable to refresh current auth user: $error": "无法刷新当前认证用户：$error",
    "Leave empty to authenticate with Authorization: Bearer.": "留空则使用 Authorization: Bearer 认证。",
    "You are a concise and reliable local assistant.": "你是一个简洁、可靠的本地助手。",
    # Models / chat / downloads / adapters / benchmarks.
    "No model loaded": "未加载模型",
    "No projects": "暂无项目",
    "No novel project": "暂无小说项目",
    "No prompt template": "暂无提示词模板",
    "No templates": "暂无模板",
    "No chapters": "暂无章节",
    "No description": "暂无描述",
    "No runs yet.": "暂无运行记录。",
    "No samples yet.": "暂无样本。",
    "No report yet.": "暂无报告。",
    "No generated report yet.": "暂无生成报告。",
    "No score": "暂无评分",
    "No overall score": "暂无总分",
    "Not generated yet.": "尚未生成。",
    "Stream": "流式输出",
    "System Prompt": "系统提示词",
    "Assistant": "助手",
    "User": "用户",
    "Send": "发送",
    "Provider": "提供方",
    "ModelScope model_id": "ModelScope 模型 ID",
    "ModelScope / 魔塔社区": "ModelScope / 魔塔社区",
    "Allow patterns，用逗号分隔": "允许文件模式，用逗号分隔",
    "Ignore patterns，用逗号分隔": "忽略文件模式，用逗号分隔",
    "No registered adapter yet.": "暂无已注册适配器。",
    "Adapter is registered but not auto activated.": "适配器已注册，但不会自动启用。",
    "Only completed fine-tune runs with a registered adapter can be evaluated.": "只有已完成且注册了适配器的微调任务才能评估。",
    "case_id: ${caseDto.caseId}": "用例 ID：${caseDto.caseId}",
    "mode: ${caseDto.mode}": "模式：${caseDto.mode}",
    "template_id: ${caseDto.templateId ?? '-'}": "模板 ID：${caseDto.templateId ?? '-'}",
    "session_id: ${session.sessionId}": "会话 ID：${session.sessionId}",
    "base_model_id: ${session.baseModelId}": "基础模型 ID：${session.baseModelId}",
    "adapter_id: ${session.adapterId}": "适配器 ID：${session.adapterId}",
    "dataset_version_id: ${session.datasetVersionId ?? '-'}": "数据集版本 ID：${session.datasetVersionId ?? '-'}",
    "finetune_run_id: ${session.finetuneRunId ?? '-'}": "微调任务 ID：${session.finetuneRunId ?? '-'}",
    "Failed: ${result.errorCode ?? ''} ${result.errorMessage ?? ''}": "失败：${result.errorCode ?? ''} ${result.errorMessage ?? ''}",
    "status: ${result?.status ?? '-'}": "状态：${result?.status ?? '-'}",
    "adapter_win_count: ${report.adapterWinCount}": "适配器胜出次数：${report.adapterWinCount}",
    "base_win_count: ${report.baseWinCount}": "基础模型胜出次数：${report.baseWinCount}",
    "average_base_score: ${report.averageBaseScore ?? '-'}": "基础模型平均分：${report.averageBaseScore ?? '-'}",
    "average_adapter_score: ${report.averageAdapterScore ?? '-'}": "适配器平均分：${report.averageAdapterScore ?? '-'}",
    "recommendation: ${report.recommendation}": "建议：${report.recommendation}",
    "Adapter: None": "适配器：无",
    "Adapter: $adapter": "适配器：$adapter",
    "Adapter: $adapterLabel": "适配器：$adapterLabel",
    "Model: $modelLabel": "模型：$modelLabel",
    "Backend: $backendStatus": "后端：$backendStatus",
    "Jobs: $runningJobs running": "任务：$runningJobs 个运行中",
    "Load current model": "加载当前模型",
    "Open Adapter": "打开适配器",
    "No adapter evaluation sessions yet.": "暂无适配器评估会话。",
    "TTFT: ${map['ttft_seconds'] ?? 'n/a'}": "首 Token 延迟：${map['ttft_seconds'] ?? 'n/a'}",
    "Token/s: ${map['tokens_per_second'] ?? 'n/a'}": "Token/s：${map['tokens_per_second'] ?? 'n/a'}",
    "Peak memory: ${map['peak_cuda_reserved'] ?? map['peak_vram'] ?? 'n/a'}": "峰值显存：${map['peak_cuda_reserved'] ?? map['peak_vram'] ?? 'n/a'}",
    "Error: ${map['error']}": "错误：${map['error']}",
    # Novel Studio.
    "Novel Studio Dashboard": "小说工作台仪表盘",
    "Novel Studio is disabled": "小说工作台已禁用",
    "Novel Studio is planned.": "小说工作台已规划。",
    "Novel Studio roadmap": "小说工作台路线图",
    "Novel projects are stored locally in SQLite.": "小说项目保存在本地 SQLite 中。",
    "Enable features.novel_studio.enabled and refresh capabilities.": "请启用 features.novel_studio.enabled 并刷新能力。",
    "Refresh capabilities": "刷新能力",
    "Refresh health": "刷新健康状态",
    "Workflow map": "工作流地图",
    "Recent activity": "最近活动",
    "Authoring path": "创作路径",
    "Improvement path": "改进路径",
    "Project → Chapters → Prompt": "项目 → 章节 → 提示词",
    "Context preview → Writing": "上下文预览 → 写作",
    "Save to Draft only when you choose it": "仅在你选择时保存到草稿",
    "Approved Revision → Dataset": "已批准修订 → 数据集",
    "Confirm recipe → Fine-tune": "确认配方 → 微调",
    "Compare adapters → Evaluation": "对比适配器 → 评估",
    "Dataset / training / evaluation remain explicit user actions": "数据集 / 训练 / 评估仍需用户显式执行",
    "No generation, Prompt Studio, Revision, Dataset, or FineTune workflow is connected.": "尚未连接生成、提示词工作室、修订、数据集或微调工作流。",
    "Status: planned / not implemented.": "状态：已规划 / 未实现。",
    "Open Diagnostics": "打开诊断",
    "New / Open Project": "新建 / 打开项目",
    "Create a project to start building the foundation library.": "创建项目，开始搭建基础资料库。",
    "Stage 1 boundary": "阶段 1 边界",
    "Stage 1 foundation: projects, chapters, characters, and world bible. No AI generation is connected.": "阶段 1 基础：项目、章节、人物和世界观设定；不连接 AI 生成。",
    "Stage 2: template versions, variable validation, and render preview only. No model generation is connected.": "阶段 2：模板版本、变量校验与渲染预览；不连接模型生成。",
    "Stage 3：选择、排序并按预算装配小说资料，不调用模型。": "阶段 3：选择、排序并按预算装配小说资料，不调用模型。",
    "Stage 4：复用 ContextAssembler、PromptRenderer 与本地 Runtime 生成小说草稿。": "阶段 4：复用 ContextAssembler、PromptRenderer 与本地 Runtime 生成小说草稿。",
    "Stage 5：人工修订、Diff、评分、审核和数据集候选标记。": "阶段 5：人工修订、Diff、评分、审核和数据集候选标记。",
    "Stage 6：从 approved revision candidates 构建 SFT samples 并导出 draft JSONL。": "阶段 6：从已批准修订候选构建 SFT 样本并导出草稿 JSONL。",
    "Stage 8 trains LoRA/QLoRA adapters. 适配器评估与基础模型对比属于 Stage 9。": "阶段 8 训练 LoRA/QLoRA 适配器。适配器评估与基础模型对比属于阶段 9。",
    "Stage 9：同一提示下对比基础模型与 Adapter 输出，人工评分并生成轻量报告。": "阶段 9：同一提示下对比基础模型与适配器输出，人工评分并生成轻量报告。",
    "Stage 10：管理长篇小说 Memory、检索预览、章节摘要版本与 ContextAssembler 注入。": "阶段 10：管理长篇小说记忆、检索预览、章节摘要版本与 ContextAssembler 注入。",
    "Stage 11: automatic heuristics, optional local model judge, findings, manual scores and reports.": "阶段 11：自动启发式评估、可选本地模型裁判、发现项、人工评分和报告。",
    # Novel project pages.
    "Create project": "创建项目",
    "Create chapter outlines and local drafts only.": "仅创建章节大纲和本地草稿。",
    "Create character": "创建人物",
    "Create entry": "创建条目",
    "Delete project": "删除项目",
    "Delete project?": "删除项目？",
    "This performs a soft delete. Child records are kept but hidden by default.": "这会执行软删除。子记录会保留，但默认隐藏。",
    "Project title": "项目标题",
    "Chapter title": "章节标题",
    "Character name": "人物名称",
    "Entry title": "条目标题",
    "Target style": "目标文风",
    "Target audience": "目标读者",
    "Genre": "题材",
    "Slug": "标识",
    "Outline": "大纲",
    "Plot Threads": "剧情线",
    # Prompt / context / writing.
    "Prompt / Context Snapshot": "提示词 / 上下文快照",
    "Context / Prompt Preview": "上下文 / 提示词预览",
    "Render preview": "渲染预览",
    "Render Preview": "渲染预览",
    "Render Context Preview": "渲染上下文预览",
    "Rendered prompt": "已渲染提示词",
    "Copy rendered prompt": "复制已渲染提示词",
    "Copy variables JSON": "复制变量 JSON",
    "Use Ensure defaults or create a prompt template.": "请使用“确保默认模板”或创建提示词模板。",
    "Create or ensure default templates first.": "请先创建或确保默认模板存在。",
    "Ensure defaults": "确保默认模板",
    "Assemble": "装配",
    "Missing variables: ${result.missingVariables.join(', ')}": "缺失变量：${result.missingVariables.join(', ')}",
    "Warnings: ${result.warnings.join(', ')}": "警告：${result.warnings.join(', ')}",
    "Writing Workspace": "写作工作区",
    "Save to Draft": "保存到草稿",
    "Append to Draft": "追加到草稿",
    "Save draft": "保存草稿",
    "Edit as Revision": "作为修订编辑",
    "View Revision": "查看修订",
    "Create Revision": "创建修订",
    "No original text.": "暂无原文。",
    "Edit the revision text here.": "在这里编辑修订文本。",
    "Autosaving": "自动保存中",
    "Autosaved $lastAutosaveAt": "$lastAutosaveAt 已自动保存",
    "No autosave yet": "尚未自动保存",
    "Memory / RAG": "记忆 / RAG",
    "Memory top_k": "记忆 top_k",
    "Max tokens": "最大 Token 数",
    "Temperature": "温度",
    "Top P": "Top P",
    "Repeat penalty": "重复惩罚",
    # Revisions / datasets.
    "Revision Review": "修订审阅",
    "Revision Records": "修订记录",
    "Revision Handoff": "修订交接",
    "Revision stays separate from final_content": "修订稿与 final_content 保持分离",
    "Human edited assets created from writing generations or drafts.": "由写作生成结果或草稿创建的人工修订资产。",
    "Dataset candidate": "数据集候选",
    "Candidate flag only; no training sample is created.": "仅设置候选标记，不创建训练样本。",
    "Quality notes": "质量备注",
    "User Score": "用户评分",
    "Reviewer id": "审阅人 ID",
    "Edit Tags": "修改标签",
    "Save Revision": "保存修订",
    "Select a revision to review.": "请选择要审阅的修订。",
    "No revision selected.": "未选择修订。",
    "Dataset Builder": "数据集构建器",
    "Datasets": "数据集",
    "Dataset Versions": "数据集版本",
    "DatasetVersion": "数据集版本",
    "Frozen immutable dataset artifact for Stage 8 preparation.": "为阶段 8 准备的冻结且不可变的数据集产物。",
    "Frozen: old DatasetVersion is immutable; new sample changes will mark dirty.": "已冻结：旧数据集版本不可变；新的样本变更会标记为 dirty。",
    "split.strategy": "拆分策略",
    "near duplicate threshold": "近似重复阈值",
    "Manifest v${version!.version}": "清单 v${version!.version}",
    "manifest: ${version!.manifestPath}": "清单路径：${version!.manifestPath}",
    "train: ${version!.trainPath}": "训练集：${version!.trainPath}",
    "val: ${version!.valPath ?? '-'}": "验证集：${version!.valPath ?? '-'}",
    "tokens: ${version!.trainTokenEstimate} train / ${version!.valTokenEstimate} val": "Token：训练 ${version!.trainTokenEstimate} / 验证 ${version!.valTokenEstimate}",
    "Split preview: ${version!.trainSampleCount} train / ${version!.valSampleCount} val, duplicates excluded ${version!.rejectedDuplicateCount}.": "拆分预览：训练 ${version!.trainSampleCount} / 验证 ${version!.valSampleCount}，已排除重复 ${version!.rejectedDuplicateCount}。",
    "Revision: ${sample.revisionId ?? '-'}": "修订：${sample.revisionId ?? '-'}",
    "Quality score: ${sample.qualityScore ?? '-'}": "质量评分：${sample.qualityScore ?? '-'}",
    "Draft export only. DatasetVersion, train/val split, and training are Stage 7+.": "仅导出草稿。数据集版本、训练/验证拆分和训练属于阶段 7+。",
    "Bulk from accepted revisions": "从已接受修订批量构建",
    "New Dataset": "新建数据集",
    "Create Dataset": "创建数据集",
    "Add Revision to Dataset": "添加修订到数据集",
    "Please mark this revision as Dataset Candidate first.": "请先将该修订标记为数据集候选。",
    "Add to Dataset": "添加到数据集",
    "Create SFT Sample": "创建 SFT 样本",
    "Export SFT JSONL": "导出 SFT JSONL",
    "Mark Ready": "标记为就绪",
    "Freeze": "冻结",
    "Freeze DatasetVersion": "冻结数据集版本",
    "No validation": "不使用验证集",
    "Group by chapter": "按章节分组",
    "Group by project": "按项目分组",
    "Random by sample": "按样本随机",
    "Exact hash dedupe": "精确哈希去重",
    "Near duplicate warning": "近似重复警告",
    "No dedupe warnings.": "没有去重警告。",
    "Project filter": "项目筛选",
    "Chapter filter": "章节筛选",
    "Type filter": "类型筛选",
    "Status filter": "状态筛选",
    "Select a dataset.": "请选择数据集。",
    "Select a sample.": "请选择样本。",
    "Select a frozen version.": "请选择冻结版本。",
    "Select a DatasetVersion to view manifest.": "请选择数据集版本查看清单。",
    "No frozen DatasetVersion yet.": "暂无冻结的数据集版本。",
    "Save Sample": "保存样本",
    "Approve Sample": "批准样本",
    "Reject Sample": "拒绝样本",
    "review notes": "审阅备注",
    "Training Recipe Preview": "训练配方预览",
    "Recommend Recipe": "推荐配方",
    "Confirm Recipe": "确认配方",
    "Confirmed recipe does not start training. Stage 8 will consume it.": "确认配方不会启动训练，阶段 8 会使用它。",
    "Recommend and confirm a draft recipe only; no training is started.": "仅推荐并确认草稿配方，不启动训练。",
    "Run preflight before creating a training run.": "创建训练任务前请先运行预检。",
    "Save Recipe Config": "保存配方配置",
    "method: ${widget.recipe!.method} · status: ${widget.recipe!.status}": "方法：${widget.recipe!.method} · 状态：${widget.recipe!.status}",
    "estimated VRAM: ${widget.recipe!.estimatedVramGb ?? '-'} GB": "预计显存：${widget.recipe!.estimatedVramGb ?? '-'} GB",
    "estimated time: ${widget.recipe!.estimatedTrainTimeMinutes ?? '-'} min": "预计耗时：${widget.recipe!.estimatedTrainTimeMinutes ?? '-'} 分钟",
    "config: ${widget.recipe!.recommendedConfig}": "配置：${widget.recipe!.recommendedConfig}",
    # Fine-tune.
    "Fine-tune Center": "微调中心",
    "Fine-tune Runs": "微调任务",
    "Fine-tune runs": "微调任务",
    "Create Fine-tune Run": "创建微调任务",
    "Create Run": "创建任务",
    "Preflight passed.": "预检通过。",
    "Preflight has ${widget.preflight!.errors.length} errors.": "预检发现 ${widget.preflight!.errors.length} 个错误。",
    "Checkpoints": "检查点",
    "Resume from Last": "从最近检查点恢复",
    "Select a fine-tune run.": "请选择微调任务。",
    "Chart TODO: table view is used in Stage 8 minimum UI.": "图表待办：阶段 8 最小 UI 使用表格视图。",
    # Adapter evaluation / evaluation center.
    "Adapter Evaluation": "适配器评估",
    "Adapter comparison": "适配器对比",
    "Base vs Adapter case": "基础模型 vs 适配器用例",
    "Compare continuation quality.": "对比续写质量。",
    "Open Full Evaluation": "打开完整评估",
    "New Session": "新建会话",
    "New Run": "新建运行",
    "Add Case": "添加用例",
    "Run Case": "运行用例",
    "Refresh Case": "刷新用例",
    "Run Session": "运行会话",
    "Generate Report": "生成报告",
    "Create Evaluation Case": "创建评估用例",
    "Create Evaluation Session": "创建评估会话",
    "Create Evaluation Run": "创建评估运行",
    "Novel evaluation": "小说评估",
    "Create Case": "创建用例",
    "Save Score": "保存评分",
    "Create Revision from ${result.variant}": "从 ${result.variant} 创建修订",
    "Create a Stage 5 revision candidate from a selected output. This does not create training samples.": "从选定输出创建阶段 5 修订候选，不会创建训练样本。",
    "Select a case to compare outputs.": "请选择用例以对比输出。",
    "Select an adapter evaluation session.": "请选择适配器评估会话。",
    "No cases. Add a case before running evaluation.": "暂无用例。请先添加用例再运行评估。",
    "No evaluation runs yet.": "暂无评估运行。",
    "No findings. Nice and quiet in the machinery room.": "暂无发现项。机房里安静得很。",
    "No metrics yet. Start or create an evaluation run.": "暂无指标。请启动或创建一个评估运行。",
    "Select an evaluation run.": "请选择评估运行。",
    "Select or generate a report.": "请选择或生成报告。",
    "Evaluation Center": "评估中心",
    "Evaluation Report": "评估报告",
    "Evaluation runs": "评估运行",
    "Evaluators": "评估器",
    "Manual Evaluation": "人工评估",
    "Manual evaluation": "人工评估",
    "Manual notes": "人工备注",
    "Save Manual Score": "保存人工评分",
    "Automatic metrics": "自动指标",
    "Run Evaluation": "运行评估",
    "Run name": "运行名称",
    "Use local model judge": "使用本地模型裁判",
    "Optional; uses local Runtime only.": "可选；仅使用本地 Runtime。",
    "Local judge model id": "本地裁判模型 ID",
    "Target type": "目标类型",
    "Target id": "目标 ID",
    "Project id (optional filter/reference)": "项目 ID（可选筛选 / 引用）",
    "Chapter id (optional reference)": "章节 ID（可选引用）",
    "Overall 1-5": "总分 1-5",
    "Overall ${score.overallScore!.toStringAsFixed(1)}": "总分 ${score.overallScore!.toStringAsFixed(1)}",
    "score ${score.toStringAsFixed(1)}": "评分 ${score.toStringAsFixed(1)}",
    "Saved scores (${widget.scores.length})": "已保存评分（${widget.scores.length}）",
    "no score": "暂无评分",
    "chapter_id, generation_id, revision_id, retrieval_id, session_id, or project_id": "chapter_id、generation_id、revision_id、retrieval_id、session_id 或 project_id",
    "Boundary: Evaluation Center only reads existing assets. It never creates training samples or rewrites draft/final content.": "边界：评估中心只读取现有资产，不创建训练样本，也不重写草稿或定稿内容。",
    "Automatic evaluation is advisory only. It does not modify novel content or training data.": "自动评估仅供参考，不会修改小说正文或训练数据。",
    "Evaluation reads existing Novel Studio assets only. It does not rewrite chapters, create training samples, or start fine-tuning.": "评估只读取现有小说工作台资产，不会重写章节、创建训练样本或启动微调。",
    "Evaluation for ${run.adapterName}": "${run.adapterName} 的评估",
    "Created from fine-tune run ${run.runId}.": "由微调任务 ${run.runId} 创建。",
    "Created from Adapter Evaluation.": "由适配器评估创建。",
    "Evaluation for generation $generationId": "生成记录 $generationId 的评估",
    "Evaluation for revision $revisionId": "修订 $revisionId 的评估",
    "Evaluation for memory retrieval $retrievalId": "记忆检索 $retrievalId 的评估",
    "Evaluation for adapter session $sessionId": "适配器会话 $sessionId 的评估",
    # Memory / RAG.
    "Memory / RAG Center": "记忆 / RAG 中心",
    "Manual Memory": "手动记忆",
    "Manual Summary": "手动摘要",
    "Chapter Summary": "章节摘要",
    "Retrieval Preview": "检索预览",
    "Retrieved Memory Preview": "检索记忆预览",
    "Query Text": "查询文本",
    "Retrieve": "检索",
    "Evaluate": "评估",
    "Rebuild Index": "重建索引",
    "Build from Novel Data": "从小说资料构建",
    "Create Manual Memory Note": "创建手动记忆笔记",
    "Create manual memory note": "创建手动记忆笔记",
    "Create Summary": "创建摘要",
    "Generate Summary": "生成摘要",
    "Archive current document": "归档当前文档",
    "Index Status": "索引状态",
    "Index status unavailable.": "索引状态不可用。",
    "Select a memory document.": "请选择记忆文档。",
    "Source Type": "来源类型",
    "max memory tokens": "最大记忆 Token 数",
    "retrieval: ${result!.retrievalId ?? '-'} · selected ${result!.selectedChunks.length} · tokens ${result!.totalTokenEstimate}": "检索：${result!.retrievalId ?? '-'} · 已选择 ${result!.selectedChunks.length} · Token ${result!.totalTokenEstimate}",
    # Diagnostics / storage.
    "Diagnostics failed": "诊断失败",
    "Diagnostics package exported": "诊断包已导出",
    "Copy export result": "复制导出结果",
    "Refresh checks": "刷新检查",
    "Export diagnostics": "导出诊断",
    "Redacted": "已脱敏",
    "Health and system": "健康与系统",
    "No capability snapshot": "暂无能力快照",
    "Click Refresh checks to load diagnostics capabilities.": "点击“刷新检查”加载诊断能力。",
    "Preview cleanup": "预览清理",
    "Execute cleanup": "执行清理",
    "Local paths restricted": "本地路径受限",
    "Runtime\n${runtime ?? {}}\n\nHealth\n${health ?? {}}\n\nSystem\n${system ?? {}}\n\nPreview\n${preview ?? {}}": "Runtime\n${runtime ?? {}}\n\n健康状态\n${health ?? {}}\n\n系统\n${system ?? {}}\n\n预览\n${preview ?? {}}",
    "API/DTO foundation exists. Full editing UI is planned for a later Stage 1 iteration. Current records: $count.": "API/DTO 基础已存在。完整编辑 UI 计划在后续阶段 1 迭代补齐。当前记录数：$count。",
    "Create template": "创建模板",
    "variables_schema JSON": "变量结构 JSON",
    "default_values JSON": "默认值 JSON",
    "variables JSON": "变量 JSON",
    "Scope: ${template.scope}": "范围：${template.scope}",
    "prompt_hash: ${preview.promptHash}": "提示词哈希：${preview.promptHash}",
    "prompt_hash: ${result.promptHash}": "提示词哈希：${result.promptHash}",
    "RAG question": "RAG 问题",
    "Evaluate Revision": "评估修订",
    "Generation ${revision.generationId}": "生成记录 ${revision.generationId}",
    "User ID (optional)": "用户 ID（可选）",
    "enabled=${user.enabled}  key=${user.apiKeyMasked ?? \"***\"}": "已启用=${user.enabled}  Key=${user.apiKeyMasked ?? \"***\"}",
    "GPU tasks": "GPU 任务",
    "Show Retrieved Memory": "显示检索记忆",
    # Additional visible strings found during archive review.
    "${item.results.length} results": "${item.results.length} 个结果",
    "Type: ${promptTypeLabels[template.type] ?? template.type}": "类型：${promptTypeLabels[template.type] ?? template.type}",
    "Memory system is not available.": "记忆系统不可用。",
    "${version.trainSampleCount} train / ${version.valSampleCount} val · ${version.warningCount} warnings": "训练 ${version.trainSampleCount} / 验证 ${version.valSampleCount} · 警告 ${version.warningCount}",
    "${value.assembly.estimatedTokens} tokens · ${value.assembly.estimatedChars} chars": "Token ${value.assembly.estimatedTokens} · 字符 ${value.assembly.estimatedChars}",
    "${record.outputCharCount} chars · ${record.createdAt}": "${record.outputCharCount} 字符 · ${record.createdAt}",
    "估算 $estimatedTokens tokens / ${result!.estimatedChars ?? 0} 字符": "估算 $estimatedTokens Token / ${result!.estimatedChars ?? 0} 字符",
}


STRING_RE = re.compile(
    r"(?P<prefix>r)?(?P<quote>'''|\"\"\"|'|\")(?P<body>.*?)(?P=quote)",
    re.DOTALL,
)


def escape_body(value: str, quote: str) -> str:
    if quote in {"'", '"'}:
        value = value.replace("\\", "\\\\")
        value = value.replace(quote, "\\" + quote)
    return value


def localize_file(path: Path) -> bool:
    text = path.read_text(encoding="utf-8")

    def repl(match: re.Match[str]) -> str:
        body = match.group("body")
        translated = ZH.get(body)
        if translated is None:
            return match.group(0)
        return f"{match.group('prefix') or ''}{match.group('quote')}{escape_body(translated, match.group('quote'))}{match.group('quote')}"

    updated = STRING_RE.sub(repl, text)
    if updated == text:
        return False
    path.write_text(updated, encoding="utf-8", newline="")
    return True


def main() -> None:
    files: set[Path] = set()
    for pattern in TARGET_GLOBS:
        files.update(FLUTTER_LIB.glob(pattern))
    changed = [path for path in sorted(files) if localize_file(path)]
    print(f"localized {len(changed)} files")
    for path in changed:
        print(path.relative_to(ROOT).as_posix())


if __name__ == "__main__":
    main()
